# Shared secret resolution, sourced by both services' run scripts.
#
# Priority order:
#   1. mcp_auth_token option, if set - an explicit, stable value.
#   2. disable_auth option, if true - no secret at all (fully open,
#      old default behavior; opt-in only).
#   3. otherwise, auto-generate a 128-bit URL-safe secret on first run and
#      persist it to /data so it (and the URLs built from it) survive
#      restarts/updates, and stay in sync between the bridge and MCP server
#      services without a startup race.

WHATSAPP_MCP_SECRET_PATH="/data/secret_path.txt"

# Only the bridge service (which starts first and has no reason to wait on
# anything) should call this - it generates and persists a secret if none
# exists yet. The MCP server must use wait_for_shared_secret below instead,
# so the two services can't independently generate two different secrets.
resolve_or_generate_shared_secret() {
    if bashio::config.has_value 'mcp_auth_token'; then
        bashio::config 'mcp_auth_token'
        return 0
    fi

    if bashio::config.true 'disable_auth'; then
        return 0
    fi

    if [ -s "${WHATSAPP_MCP_SECRET_PATH}" ]; then
        cat "${WHATSAPP_MCP_SECRET_PATH}"
        return 0
    fi

    local generated
    generated="$(head -c16 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=')"
    printf '%s' "${generated}" > "${WHATSAPP_MCP_SECRET_PATH}"
    chmod 600 "${WHATSAPP_MCP_SECRET_PATH}"
    echo "${generated}"
}

# Waits briefly for the bridge service to have resolved/persisted the
# shared secret, then reads the same value - never generates one itself.
wait_for_shared_secret() {
    if bashio::config.has_value 'mcp_auth_token'; then
        bashio::config 'mcp_auth_token'
        return 0
    fi

    if bashio::config.true 'disable_auth'; then
        return 0
    fi

    local i
    for ((i = 0; i < 30; i++)); do
        if [ -s "${WHATSAPP_MCP_SECRET_PATH}" ]; then
            cat "${WHATSAPP_MCP_SECRET_PATH}"
            return 0
        fi
        sleep 1
    done

    bashio::log.warning "Timed out waiting for the shared secret to be generated by the bridge service; the MCP server will start without authentication."
    return 0
}
